spring:
  datasource:
    url: jdbc:tc:postgresql:16:///humanwrites
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-client-id
            client-secret: test-client-secret

logging:
  level:
    com.humanwrites: DEBUG
